services:
  nginx:
    build:            ./requirements/nginx
    container_name:   nginx
    #depends_on:
    #                  -wordpress
    ports:
                      - "443:443"
    volumes:
                      - /home/bmatos-d/data/wordpress:/var/www/wordpress:ro
    restart:
                      always

    
  
  #wordpress:
  #  build:            ./requirements/wordpress
  #  container_name:   wordpress
  #  depends_on:
  #                    - mariadb
  #  volumes:
  #                    - /home/bmatos-d/data/wordpress:/var/www/html
  #  restart: 
  #                    always
  #
  #mariadb:
  #  build:            ./requirements/mariadb
  #  container_name:   mariadb
  #  volumes:
  #                    - /home/bmatos-d/data/mysql:/var/lib/mysql
  #  restart:
  #                    always
  
volumes:
  - /home/bmatos-d/data/wordpress:/var/www/html
  - /home/bmatos-d/data/mysql:/var/lib/mysql
  