services:
  nginx:
    build:            ./requirements/nginx
    container_name:   nginx
    #depends_on:
    #                  -wordpress
    ports:
                      -"443:443"
    volumes:
                      -wordpress_volume:/var/www/wordpress:ro
    restart:
                      always

    
  
  #wordpress:
  #  build:            ./requirements/wordpress
  #  container_name:   wordpress
  #  depends_on:
  #                    -mariadb
  #  volumes:
  #                    -wordpress_volume:/var/www/wordpress
  #  restart: 
  #                    always
  #
  #mariadb:
  #  build:            ./requirements/mariadb
  #  container_name:   mariadb
  #  volumes:
  #                    -wordpress_database:/var/lib/mysql
  #  restart:
  #                    always
  
volumes:
  wordpress_volume:
    driver_opts:
      device:         /home/bmatos-d/data/wordpress

  wordpress_database:
    driver_opts:
      device:         /home/bmatos-d/data/mysql
  