all 	: up

up		:
	docker-compose -f ./srcs/docker-compose.yml up

down	:
	docker-compose -f ./srcs/docker-compose.yml down

logs	:
	docker-compose -f ./srcs/docker-compose.yml logs

ps		:
	docker-compose -f ./srcs/docker-compose.yml ps

clean	:
	docker 